{% set version = "0.47.1" %}

package:
  name: vscode-go-debug-adapter
  version: {{ version }}

source:
  url: https://github.com/golang/vscode-go/archive/v{{ version }}.tar.gz
  sha256: f71b17c169a47e74d1e81b47905036daf5919f019f0a090c320681878d5a41d9

build:
  noarch: generic
  number: 0

requirements:
  host:
    - go-yq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - vscode-go-debug-adapter &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/golang/vscode-go
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Go debug adapter
  dev_url: https://github.com/golang/vscode-go

extra:
  recipe-maintainers:
    - danielnachun
