{% set version = "0.51.0" %}

package:
  name: vscode-go-debug-adapter
  version: {{ version }}

source:
  url: https://github.com/golang/vscode-go/archive/v{{ version }}.tar.gz
  sha256: 8d63354d5adaa30b6a71f9605c62dd9d6e50655fadd160060ddb71563ef57638

build:
  noarch: generic
  number: 0

requirements:
  host:
    - go-yq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - vscode-go-debug-adapter &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/golang/vscode-go
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Go debug adapter
  dev_url: https://github.com/golang/vscode-go

extra:
  recipe-maintainers:
    - danielnachun
