{% set version = "0.41.4" %}

package:
  name: vscode-go-debug-adapter
  version: {{ version }}

source:
  url: https://github.com/golang/vscode-go/archive/v{{ version }}.tar.gz
  sha256: 6c6642600c26b5701014f22d4ebff2069318f8bee27c1eac2c7edccea473cd57

build:
  noarch: generic
  number: 0

requirements:
  host:
    - go-yq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - vscode-go-debug-adapter &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/golang/vscode-go
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Go debug adapter
  dev_url: https://github.com/golang/vscode-go

extra:
  recipe-maintainers:
    - danielnachun
